version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tutorial_v2
      - POSTGRES_USER=hello 
      - POSTGRES_PASSWORD=1
  web: 
    build: .
    command: python3 manage.py runserver 0.0.0.0:8001
    volumes:
      - ./data
    ports:
      - "8001:8001"
    depends_on:
      - db 
