# Generated by Django 4.0.6 on 2022-07-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='adviser_image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='adviser_name',
        ),
    ]
