# Generated by Django 4.0.6 on 2022-07-07 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='lesson.adviser'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='course.category'),
        ),
    ]
