# Generated by Django 4.0.6 on 2022-07-20 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='courseimage/', verbose_name='Фото курса')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagecourse', to='course.course')),
            ],
        ),
    ]
