# Generated by Django 4.0.6 on 2022-07-08 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_image', models.ImageField(upload_to='courseimage/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseimage', to='course.course')),
            ],
        ),
    ]
