# Generated by Django 4.0.6 on 2022-07-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_remove_lesson_group_lesson_delete_grouplesson'),
        ('course', '0002_alter_course_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(related_name='lesson', to='lesson.lesson'),
        ),
    ]
