# Generated by Django 4.0.6 on 2022-07-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_imagecourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default=1, upload_to='courseimage/', verbose_name='Фото курса'),
            preserve_default=False,
        ),
    ]
