# Generated by Django 4.1 on 2022-08-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='adviser',
        ),
    ]
