# Generated by Django 4.0.6 on 2022-07-14 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_searchhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseregister',
            options={'verbose_name': 'Запись на курс', 'verbose_name_plural': 'Записи на курс'},
        ),
        migrations.AlterModelOptions(
            name='savedcourse',
            options={'verbose_name': 'Сохраненный курс', 'verbose_name_plural': 'Сохраненные курсы'},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'verbose_name': 'История поиска', 'verbose_name_plural': 'История поиска'},
        ),
        migrations.AddField(
            model_name='course',
            name='student_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courseregister',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseregister', to='course.course', verbose_name='К какому курсу'),
        ),
        migrations.AlterField(
            model_name='courseregister',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseregister', to=settings.AUTH_USER_MODEL, verbose_name='Какой пользователь'),
        ),
        migrations.AlterField(
            model_name='savedcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='course.course', verbose_name='Курс для сохранение'),
        ),
        migrations.AlterField(
            model_name='savedcourse',
            name='saved',
            field=models.BooleanField(default=False, verbose_name='Сохранить'),
        ),
        migrations.AlterField(
            model_name='savedcourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='item',
            field=models.CharField(max_length=50, verbose_name='Название для поиска'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchhistory', to=settings.AUTH_USER_MODEL, verbose_name='К какому пользователю принадлежит'),
        ),
    ]
