# Generated by Django 4.0.6 on 2022-07-29 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_remove_adviser_course'),
        ('course', '0003_alter_course_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='adviser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='course', to='lesson.adviser'),
            preserve_default=False,
        ),
    ]
