# Generated by Django 4.0.6 on 2022-07-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='registered_student_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
