# Generated by Django 4.0.6 on 2022-07-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_courseregister_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student_counter',
            field=models.IntegerField(blank=True),
        ),
    ]
