# Generated by Django 4.0.6 on 2022-07-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_review_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default='a.png', upload_to='courseimage/', verbose_name='Фото курса'),
            preserve_default=False,
        ),
    ]
