# Generated by Django 4.0.6 on 2022-07-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_student_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student_counter',
        ),
        migrations.AddField(
            model_name='courseregister',
            name='student_counter',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
