# Generated by Django 4.0.6 on 2022-07-20 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_student_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student_counter',
        ),
    ]
