# Generated by Django 4.0.6 on 2022-07-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_course_student_counter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregister',
            name='student_counter',
        ),
    ]
