# Generated by Django 4.0.6 on 2022-07-08 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_course_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseImage',
        ),
    ]
