# Generated by Django 4.0.6 on 2022-07-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя преподавателя')),
                ('image', models.ImageField(blank=True, default=None, upload_to='imageadviser/', verbose_name='Фото преподователя')),
            ],
            options={
                'verbose_name': 'Преподователя',
                'verbose_name_plural': 'Преподователи',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название урока')),
                ('description', models.TextField(verbose_name='Описание урока')),
                ('file', models.FileField(upload_to='lessonfile/', verbose_name='Файл с кодом в формате --> MD')),
                ('video', models.FileField(blank=True, upload_to='videolesson/', verbose_name='Усман лапуля')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
