# Generated by Django 4.0.6 on 2022-07-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviserimage',
            name='image',
            field=models.ImageField(upload_to='adviserimage'),
        ),
    ]
