# Generated by Django 4.0.6 on 2022-07-29 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_rating'),
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adviser', to='course.course'),
        ),
    ]
