# Generated by Django 4.0.6 on 2022-07-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='image',
            field=models.ImageField(default='d.png', upload_to='adviserimage', verbose_name='Фото преподователя'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdviserImage',
        ),
    ]
