# Generated by Django 4.0.6 on 2022-07-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, upload_to='videolesson/', verbose_name='Усман лапуля'),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
