# Generated by Django 4.0.6 on 2022-07-07 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        ('lesson', '0002_alter_adviserimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adviser',
            options={'verbose_name': 'Преподователя', 'verbose_name_plural': 'Преподователи'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AlterField(
            model_name='adviser',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя преподавателя'),
        ),
        migrations.AlterField(
            model_name='adviserimage',
            name='image',
            field=models.ImageField(upload_to='adviserimage', verbose_name='Фото преподователя'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='course.course', verbose_name='К какому курсу добавить урок'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(verbose_name='Описание урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(null=True, upload_to='lessonfile/', verbose_name='Файл с кодом в формате --> MD'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название урока'),
        ),
        migrations.AlterField(
            model_name='video',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='lesson.lesson', verbose_name='Видео для урока'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videolesson/', verbose_name='Усман лох/чмо/пидор'),
        ),
    ]
