# Generated by Django 4.0.6 on 2022-07-28 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_adviser_image_and_more'),
        ('lesson', '0002_adviser_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adviser', to='course.course'),
        ),
    ]
