# Generated by Django 4.0.6 on 2022-07-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_adviser_image_delete_adviserimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adviser',
            name='image',
        ),
    ]
