# Generated by Django 4.0.6 on 2022-07-14 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_courseregister_options_and_more'),
        ('lesson', '0002_remove_lesson_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouplesson',
            options={'verbose_name': 'Группа уроков', 'verbose_name_plural': 'Группа уроков'},
        ),
        migrations.AlterField(
            model_name='grouplesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouplesson', to='course.course', verbose_name='к какому курсу добавить'),
        ),
        migrations.AlterField(
            model_name='grouplesson',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название группы уроков'),
        ),
    ]
