# Generated by Django 4.0.6 on 2022-07-28 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_alter_adviser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='group_lesson',
        ),
        migrations.DeleteModel(
            name='GroupLesson',
        ),
    ]
