# Generated by Django 4.0.6 on 2022-07-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_alter_adviser_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adviser',
            name='course',
        ),
    ]
