# Generated by Django 4.0.6 on 2022-07-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_alter_adviser_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(default='f.png', upload_to='lessonfile/', verbose_name='Файл с кодом в формате --> MD'),
            preserve_default=False,
        ),
    ]
