# Generated by Django 4.0.6 on 2022-07-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_remove_adviser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='image',
            field=models.ImageField(default='e.png', upload_to='imageadviser/', verbose_name='Фото преподователя'),
            preserve_default=False,
        ),
    ]
