name: tutor


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: self-hosted

    steps:
    
    
         
      - uses: AutoModality/action-clean@v1   
      - uses: actions/checkout@v2

            
      - name: Makemigrations
        run: |
          docker-compose run web python3 manage.py makemigrations
          
      - name: Migrate
        run: |
          docker-compose run web python3 manage.py migrate
          
      - name: Collectstatic
        run: |
          docker-compose run web python3 manage.py collectstatic 
          
      - name: Run Docker-Compose
        run: |
          docker-compose up -d
